<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ModType>mod</ModType>
    <ModMain>ZoomVision.ZoomVisionMain</ModMain>
    <AutoInstallMod Condition="'$(Configuration)' == 'Debug'">true</AutoInstallMod>
  </PropertyGroup>

  <Target Name="CopyModFiles" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <ModFiles Include="$(OutputPath)output\ZoomVision\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(ModFiles)" DestinationFolder="D:\steama\steamapps\common\Dead Cells\coremod\mods\ZoomVision\%(RecursiveDir)" />
  </Target>

  <ItemGroup>
    <PackageReference Include="DeadCellsCoreModding.MDK" Version="1.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <GenerateDiffCDB>false</GenerateDiffCDB>
    <GameVersion>35</GameVersion>
    <GenerateSinglePakFile>false</GenerateSinglePakFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
