<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModType>mod</ModType>
    <ModName>KingScepterAim</ModName>
    <ModMain>KingScepterAim.KingScepterAimMain</ModMain>
    <AutoInstallMod Condition="'$(Configuration)' == 'Debug'">true</AutoInstallMod>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDiffCDB>false</GenerateDiffCDB>
    <GameVersion>35</GameVersion>
    <GenerateSinglePakFile>false</GenerateSinglePakFile>
  </PropertyGroup>

  <!-- 纯代码补丁：无需 Assets / data.cdb 数据修改 -->
  <ItemGroup>
    <PackageReference Include="DeadCellsCoreModding.MDK" Version="1.0.1" />
  </ItemGroup>

</Project>
